name: cli_tool
description: cli tools which help to create flutter project with needed pakcages, folder structures and s.o
version: 0.0.1
homepage: https://github.com/rGradov/cli_tool
environment:
  sdk: ">=2.18.5 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
